### ISSUE TITLE
.limestore.json file - Main issue

### ISSUE THREAD

**Issue by LarsCJensen** [Lundalogik/LimeBootstrapServices#10]
Instead of looking for repos with "addon-" prefix the service instead looks for a folder called .limestore. In that folder the images, metadata.json and limestore.md are placed.

If a repo has release those files are gotten from the latest release, else it is collected from master branch.

**Comment by justFredster** [comment]
From platform team: Try to keep requests to GitHub to a minimum. We have a max number of requests per "time unit" that we sometimes hit during nights when Jenkins is working.

**Comment by justFredster** [comment]
Updated title on this issue due to changes in solution plan. Here are the details as discussed in emails before, ping @LarsCJensen 

* The service should look for a file in the root called ".limestore.json". If that file does exist, the information in it should be read into the postgre database.
* The content of that file should be the same as we have in the metadata.json today, except that we add a few things as described below.
* It is possible to add several add-ons in the same file, for situations where one repository should be displayed as several entries in the Lime Store.
* An array of strings with relative paths for images on the add-on modal in Lime Store
* A string with relative path for image for thumbnail in Lime Store.
* A string with the relative path for the markdown file to be shown in Lime Store.
* A boolean to show if the web client is supported.
* A boolean to show if the desktop client is supported.
* All images and the markdown file should be placed in the resources folder (but that will not matter to the service).

The above means that the file ".limestore.json" will look something like this:

{
    "uniqueName": "erpconnector",
    "add-ons": [
        {
            "displayName": "Visma Administration (ERP Connector)",
            "description": "Transfers customers from Lime CRM to Visma Administration and shows invoice information on the customer in Lime CRM.",
            "cloudCompatible": true,
            "webClientSupported": false,
            "desktopClientSupported": true,
            "tags": [
                "sales"
            ],
            "thumbnailImage": "resources/erpconnector_small.png",
            "images": [
                "resources/erpconnector.png"
            ],
            info: "resources/limestore.md"
        }
    ]
}

And of course in this example, there should be more objects in the "add-ons" array to describe the other supported systems. Each system should be shown as a separate entry in the Lime Store.

The unique name is the one that should be used when running lip.Install.

**Comment by justFredster** [comment]
@LarsCJensen Can you break this issue down and create issues for what exactly needs to be done in the service? Add them to the ESS Team project with top priority.

**Comment by LarsCJensen** [comment]
Jag verkar inte kunna välja ESS i project.

**Comment by LarsCJensen** [comment]
Vi kanske behöver prata om punkterna förresten.

**Comment by LarsCJensen** [comment]
* It is possible to add several add-ons in the same file, for situations where one repository should be displayed as several entries in the Lime Store.

Could we discuss this a bit more?

**Comment by justFredster** [comment]
@LarsCJensen I have added the issues to the GitHub project now!

Weird that you didn't manage to add them. Did you click on "Organization" instead of "Repository"?

**Comment by LarsCJensen** [comment]
Yes I did

**Comment by justFredster** [comment]
Updated comment above with specification of .limestore.json content: Moved uniqueName inside add-ons array.

**Comment by justFredster** [comment]
Moved "tags" outside "add-ons"
